# resource config
exp_name: cifar100-mobilenetV2

# checkpoint config
model: mobilenetV2
pre_train: True

# dataset config
dataset: cifar100
batch_size: 128

# optimizer config
optim: sgd
learning_rate: 0.05

# scheduler config
scheduler: warmup_cos_lr
min_lr: 0
warm_steps: 10

# federal config
non_iid: hetero
workers: 100
active_workers: 10
federal_round: 400

## federal simulation
# local_epoch: 5

## center train
local_epoch: 10
test_batch_limit: 5
