# test_rankfl.yaml

# resource config
exp_name: cifar100-resnet110

# checkpoint config
model: resnet110

# dataset config
dataset: cifar100
batch_size: 128

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.1

# scheduler config
scheduler: warmup_cos_lr
warm_steps: 30

# federal config
non_iid: hetro
workers: 100
active_workers: 10
federal_round: 100

## federal simulation
# local_epoch: 5

## center train
local_epoch: 300
test_batch_limit: 5

