# resource config
exp_name: cifar100-resnet110

# checkpoint config
model: resnet110
pre_train: True

# dataset config
dataset: cifar100
batch_size: 128

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.1

# scheduler config
scheduler: warmup_cos_lr
min_lr: 0.0
warm_steps: 10

# federal config
non_iid: hetro
workers: 100
active_workers: 10
federal_round: 500

## federal simulation
# local_epoch: 5

## center train
local_epoch: 10
test_batch_limit: 5

