# test_rankfl.yaml

# resource config
exp_name: cifar10-resnet56

# checkpoint config
model: resnet56

# dataset config
dataset: cifar10
batch_size: 32

# optimizer config
# optim: sgd
optim: sgd_pfl
learning_rate: 0.01

# scheduler config
scheduler: step_lr
warm_steps: 10

# federal config
non_iid: hetro
workers: 100
active_workers: 10
federal_round: 100

## federal simulation
# local_epoch: 5

## center train
local_epoch: 100
test_batch_limit: 5

