# test_rankfl.yaml

# resource config
exp_name: b2n2

# checkpoint config
model: vgg16
pre_train: True

# dataset config
dataset: cifar10
batch_size: 16

# optimizer config
# optim: sgd
optim: sgd
learning_rate: 0.1

# scheduler config
scheduler: step_lr
warm_steps: 10

# prune config
rank_path: none
info_norm: 2
backward: 2
en_alpha: 0.5
en_shrink: 0.95

# federal config
local_epoch: 300
