# resource config
exp_name: cifar100-mobilenetV2

# checkpoint config
model: mobilenetV2

# dataset config
dataset: cifar100
batch_size: 128

# optimizer config
optim: sgd
learning_rate: 0.01

# scheduler config
scheduler: warmup_cos_lr
min_lr: 0.0
warm_steps: 5

# federal config
non_iid: hetro
workers: 100
active_workers: 10
federal_round: 100

## federal simulation
# local_epoch: 5

## center train
local_epoch: 300
test_batch_limit: 5
